version: '3'

services:
  db5th_next:
    build: ./next
    tty: true
    container_name: db5th_next
    volumes: 
        - ./next:/next
    ports:
      - "80:3000"
  db5th_go:
    build: ./go
    tty: true
    container_name: db5th_go
    volumes:
      - ./go:/go
    ports:
      - "8080:8080"

